name: Using hello world
on: [push]

jobs:
  hello_world_job:
    runs-on: ${{ matrix.os }}
    name: A job to say hello
    strategy:
      # To test across multiple language versions
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest ]
        node-version: [12.x, 14.x]
        
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ULL-ESIT-PL-2021/hello-js-action-EduardoEB3@v1
        id: hello
        with:
          who-to-greet: 'Eduardo Expósito Barrera: Procesadores de Lenguajes 2021'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

